[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SindbadML = "eb1d8004-2d42-4eef-b369-ed0645c101e8"
SindbadTutorials = "7150cb7e-b54a-4419-adf4-a3c5c2a90a47"

[sources]
SindbadML = {path = "../../SINDBAD/lib/SindbadML"}
SindbadTutorials = {path = "../.."}
